### ISSUE TITLE
work theme

### ISSUE THREAD

**Issue by dronov-dmitry** [nitschis/GreyEveTheme#2]
it dosn't work
https://prnt.sc/s6z0mk
but this work
https://github.com/dronov-dmitry/windows-10-dark-theme/blob/master/AllDarkEveV3.deskthemepack

**Comment by nitschis** [comment]
Are you applying it on Windows 10? Which version and edition are you using?
Thanks.

**Comment by rtropf** [comment]
@nitschis 

I don't speak/read Russian, but I'm also getting an error when trying to run this. It reads: This theme can't be applied to the desktop. Try clicking a different them

I've tried double-clicking from both my downloads folder and from C:\Users\user\AppData\Roaming\Microsoft\Windows\Themes.

If I'm running it from the wrong location, my bad. Not sure where else to run it from, though I read on a third party site to run it from [USERNAME]AppData\Local\Microsoft\Windows\Themes, but I don't have a Microsoft folder in Local.

Thanks for any help you can provide.

**Comment by nitschis** [comment]
Please post your Windows version or a screenshot of your "system" windows.

I have added a *.deskthemepack version, please test this and report back. Thank you.

**Comment by rtropf** [comment]
![About](https://user-images.githubusercontent.com/64757371/80948718-b057c200-8dc0-11ea-8291-db6304cc9635.PNG)

Double-clicking the new one doesn't "do" anything, in the sense that I do not receive any pop up or anything.

However, I'm not entirely sure that is isn't working. It's hard to tell because I already had Windows in Dark mode and set colors to "black" (or as black as MS would allow)...so I'm just honestly not real sure. I suppose I could try going back to the default Windows theme and then launching your theme again.

**Comment by nitschis** [comment]
Please try that, there are many ways to check if the theme is active. The fastest would probably be to open a legacy application/settings. For example open the device manager (right click on Start) a check if it has dark colors.

**Comment by rtropf** [comment]
So sorry for late reply. 

Device manager still has it's bright, white background. No dark colors. Thanks for the tip on how to check, that was super helpful. 

![Windows Colors](https://user-images.githubusercontent.com/64757371/81119793-82c26400-8ef9-11ea-8423-96958fada714.PNG)

**Comment by nitschis** [comment]
Thank you for your help, I finally got back to booting windows again. Looks like I just linked the files in the wrong way, please try again and report back.

**Comment by rtropf** [comment]
Dope. New one works. Cheers.
