### ISSUE TITLE
Don't have every window affeted

### ISSUE THREAD

**Issue by MeblIkea** [nitschis/GreyEveTheme#6]
Hi, how to don't have every window affected by this theme please, because it's kinda ugly on some window.
![Capture](https://user-images.githubusercontent.com/69876322/181090581-a92e5640-8592-4bef-b1c2-1618677d3de8.PNG)

**Comment by nitschis** [comment]
For things like Firefox, it is already in the README / Main github project page: 
`
In firefox - Preferences -> Color and Appearance -> Colors -> In the drop down menu, select "Never".`

Discord is an electron app, so it should easily be possible, but you have to go to discord support for that.

An application/launcher like "runas" for theme selection would be great, but a few years back I did not find anything, maybe if you search for it, someone has made it by now.
I have not been using Windows for a long time, because of things like bad theme support, and my overall experience is much better on Linux for me.

**Comment by MeblIkea** [comment]
Hi, thanks for your reply.
I founded how to disable high contrast theme in Windows Settings!
You just have to goto settings → Accessibility and then Uncheck "Sync contrast settings".
